require_relative 'zadt/AbstractDataTypes/ADT.rb'
require_relative 'zadt/AbstractDataTypes/MinMaxStackQueue/Stack.rb'
require_relative 'zadt/AbstractDataTypes/MinMaxStackQueue/Queue.rb'
require_relative 'zadt/AbstractDataTypes/MinMaxStackQueue/StackQueue.rb'
require_relative 'zadt/AbstractDataTypes/MinMaxStackQueue/MinMaxStack.rb'
require_relative 'zadt/AbstractDataTypes/MinMaxStackQueue/MinMaxStackQueue.rb'

require_relative 'zadt/AbstractDataTypes/Graph/vertex.rb'
require_relative 'zadt/AbstractDataTypes/Graph/edge.rb'
require_relative 'zadt/AbstractDataTypes/Graph/graph.rb'
require_relative 'zadt/AbstractDataTypes/Graph/face.rb'
require_relative 'zadt/AbstractDataTypes/Graph/face_graph.rb'

require_relative 'zadt/AbstractDataTypes/Geometrics/universe.rb'
require_relative 'zadt/AbstractDataTypes/Geometrics/sphere.rb'
